import { jsPDF } from 'jspdf';
import { EvidenceVerificationResult } from './types';

const MARGIN = 15;
const PAGE_WIDTH = 210; // A4 mm
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2;

// Builds and downloads a self-contained PDF evidence report from a
// completed verification result — claim, verdict, confidence, every piece
// of evidence, every source with its URL, and the generation date, so the
// user can independently verify the result outside the app.
export function downloadEvidenceReportPdf(result: EvidenceVerificationResult): void {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  let y = MARGIN;

  const ensureSpace = (needed: number) => {
    if (y + needed > 297 - MARGIN) {
      doc.addPage();
      y = MARGIN;
    }
  };

  const writeWrapped = (text: string, fontSize: number, lineGap = 5, style: 'normal' | 'bold' = 'normal') => {
    doc.setFont('helvetica', style);
    doc.setFontSize(fontSize);
    const lines = doc.splitTextToSize(text, CONTENT_WIDTH);
    ensureSpace(lines.length * lineGap + 2);
    doc.text(lines, MARGIN, y);
    y += lines.length * lineGap + 2;
  };

  const heading = (text: string) => {
    ensureSpace(10);
    doc.setDrawColor(209, 131, 90); // #D1835A
    doc.setLineWidth(0.5);
    doc.line(MARGIN, y, MARGIN + CONTENT_WIDTH, y);
    y += 6;
    writeWrapped(text, 13, 5.5, 'bold');
  };

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(17);
  doc.text('Baltic Sea News — Evidence Report', MARGIN, y);
  y += 8;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(110, 110, 110);
  doc.text(`Generated ${new Date(result.generatedAt).toLocaleString('en-GB')}`, MARGIN, y);
  doc.setTextColor(20, 20, 20);
  y += 8;

  heading('Claim');
  writeWrapped(result.claim, 11);
  if (result.originalInput !== result.claim) {
    writeWrapped(`Original input: "${result.originalInput}"`, 9, 4.5);
  }

  heading('Verdict & Confidence');
  writeWrapped(`Verdict: ${result.verdict}`, 12, 6, 'bold');
  writeWrapped(`Confidence: ${result.confidence}%`, 11);

  heading('AI Analysis');
  writeWrapped(result.aiAnalysis, 10);

  const writeEvidenceList = (title: string, items: EvidenceVerificationResult['supportingEvidence']) => {
    heading(`${title} (${items.length})`);
    if (items.length === 0) {
      writeWrapped('None found.', 10);
      return;
    }
    items.forEach((item, i) => {
      writeWrapped(`${i + 1}. ${item.summary}`, 10, 4.6, 'bold');
      writeWrapped(
        `   Publisher: ${item.publisher}  |  Reliability: ${item.reliability}/100  |  Published: ${
          item.publishedDate ?? 'unknown'
        }`,
        9,
        4.4
      );
      writeWrapped(`   Source: ${item.url}`, 9, 4.4);
      y += 1;
    });
  };

  writeEvidenceList('Supporting Evidence', result.supportingEvidence);
  writeEvidenceList('Contradicting Evidence', result.contradictingEvidence);

  heading(`Sources Used (${result.sources.length})`);
  if (result.sources.length === 0) {
    writeWrapped('No sources were used to reach this verdict.', 10);
  } else {
    result.sources.forEach((source, i) => {
      writeWrapped(`${i + 1}. ${source.name} — Reliability ${source.reliability}/100 — ${source.type.replace('_', ' ')}`, 10, 4.6);
      writeWrapped(`   ${source.url}`, 9, 4.4);
    });
  }

  heading('Verification Trail');
  result.trail.forEach((step) => {
    const mark = step.status === 'done' ? '[x]' : step.status === 'skipped' ? '[-]' : '[ ]';
    writeWrapped(`${mark} ${step.label}${step.detail ? ` — ${step.detail}` : ''}`, 9.5, 4.6);
  });

  ensureSpace(12);
  y += 4;
  doc.setFontSize(8);
  doc.setTextColor(140, 140, 140);
  writeWrapped(
    'This report was generated by an automated retrieval-augmented verification pipeline. Evidence is retrieved from third-party sources listed above; verify original sources directly before relying on this report.',
    8,
    4
  );

  const filenameSafeClaim = result.claim.slice(0, 40).replace(/[^a-z0-9]+/gi, '-').toLowerCase();
  doc.save(`baltic-sea-news-evidence-report-${filenameSafeClaim || 'claim'}.pdf`);
}
