import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'es' | 'fr' | 'de' | 'it' | 'pt' | 'nl' | 'sv' | 'da' | 'no' | 'fi' | 'pl' | 'ru';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  en: {
    'nav.home': 'Home',
    'nav.mission': 'Mission',
    'nav.features': 'Features',
    'nav.services': 'Services',
    'nav.community': 'Community',
    'nav.dashboard': 'Dashboard',
    'nav.signIn': 'Sign In',
    'nav.getStarted': 'start',
    'hero.title1': 'Connect European',
    'hero.title2': 'Students & Educators',
    'hero.title3': 'Across Borders',
    'hero.subtitle': 'Verify Information Before It Shapes Reality',
    'hero.startJourney': 'Start Your Learning Journey',
    'hero.learnMore': 'Verify a Claim',
    'stats.members': 'Student Members',
    'stats.countries': 'Countries',
    'stats.support': 'Educational Support',
    'mission.title': 'Our Mission',
    'mission.description': 'At Borderless Health, we believe that access to quality healthcare and wellness support should transcend national boundaries. Our mission is to build an inclusive, collaborative health ecosystem across Europe — where individuals, caregivers, and professionals can connect, heal, and thrive together.',
    'features.title': 'Care Without Borders',
    'features.subtitle': 'Discover our comprehensive suite of healthcare features designed to connect patients and providers across the Baltics and Europe, making cross-border care simple, accessible, and personalized.',
    'features.language.title': 'Language Exchange Programs',
    'features.language.description': 'Connect with native speakers and practice European languages through structured exchange programs.',
    'features.academic.title': 'Academic Collaboration',
    'features.academic.description': 'Join research projects and academic initiatives with students from across Europe.',
    'features.mentorship.title': 'Cross-Border Mentorship',
    'features.mentorship.description': 'Get guidance from experienced educators and professionals from different European countries.',
    'features.resources.title': 'Shared Learning Resources',
    'features.resources.description': 'Access educational materials, courses, and resources shared by the European learning community.',
    'services.title': 'Educational Services',
    'services.subtitle': 'Comprehensive educational support services connecting European students and institutions.',
    'services.online.title': 'Online Learning Platforms',
    'services.online.description': 'Access courses and educational content from top European universities and institutions.',
    'services.exchange.title': 'Student Exchange Programs',
    'services.exchange.description': 'Participate in exchange programs and study abroad opportunities across Europe.',
    'services.language.title': 'Language Learning Support',
    'services.language.description': 'Comprehensive language learning programs with native speakers from across Europe.',
    'services.research.title': 'Collaborative Research',
    'services.research.description': 'Join international research projects and academic collaborations.',
    'community.title': 'European Healthcare Community',
    'community.subtitle': 'Connect with patients, doctors, and healthcare centers from across Europe in our vibrant healthcare community.',
    'community.chat.title': 'Community Chat',
    'community.chat.description': 'Join real-time discussions with fellow students and educators from across Europe.',
    'community.forums.title': 'Study Groups & Forums',
    'community.forums.description': 'Participate in subject-specific study groups and academic discussions.',
    'community.events.title': 'Educational Events',
    'community.events.description': 'Attend webinars, workshops, and virtual conferences hosted by European institutions.',
    'footer.company': 'Borderless Learning',
    'footer.description': 'Connecting European students and educators to create a unified learning ecosystem across all borders. Education knows no boundaries.',
    'auth.login': 'Login',
    'auth.register': 'Register',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.forgotPassword': 'Forgot Password?',
    'auth.noAccount': "Don't have an account?",
    'auth.hasAccount': 'Already have an account?',
    'chat.placeholder': 'Type your message...',
    'chat.send': 'Send',
    'chat.online': 'Online'
  },
  de: {
    'nav.home': 'Startseite',
    'nav.mission': 'Mission',
    'nav.features': 'Funktionen',
    'nav.services': 'Dienste',
    'nav.community': 'Gemeinschaft',
    'nav.dashboard': 'Dashboard',
    'nav.signIn': 'Anmelden',
    'nav.getStarted': 'Loslegen',
    'hero.title1': 'Verbinde Europäische',
    'hero.title2': 'Studenten & Pädagogen',
    'hero.title3': 'Über Grenzen Hinweg',
    'hero.subtitle': 'Überbrücke Bildungslücken und fördere die Zusammenarbeit zwischen Studenten, Pädagogen und Institutionen in ganz Europa. Teile Wissen, lerne Sprachen und baue dauerhafte akademische Verbindungen auf.',
    'hero.startJourney': 'Beginne Deine Lernreise',
    'hero.learnMore': 'Mehr Erfahren',
    'stats.members': 'Studenten-Mitglieder',
    'stats.countries': 'Länder',
    'stats.support': 'Bildungsunterstützung',
    'mission.title': 'Unsere Bildungsmission',
    'mission.description': 'Bei Borderless Learning glauben wir, dass Bildung und Wissensaustausch nationale Grenzen überschreiten sollten. Unsere Mission ist es, ein einheitliches europäisches Bildungsökosystem zu schaffen, in dem Studenten und Pädagogen zusammenarbeiten, voneinander lernen und gemeinsam die Zukunft Europas gestalten können.',
    'features.title': 'Lernen Ohne Grenzen',
    'features.subtitle': 'Entdecke unser umfassendes Angebot an Bildungsfunktionen, die europäische Studenten und Pädagogen verbinden und den Wissensaustausch sowie kollaboratives Lernen auf dem gesamten Kontinent ermöglichen.',
    'features.language.title': 'Sprachaustauschprogramme',
    'features.language.description': 'Verbinde dich mit Muttersprachlern und übe europäische Sprachen durch strukturierte Austauschprogramme.',
    'features.academic.title': 'Akademische Zusammenarbeit',
    'features.academic.description': 'Beteilige dich an Forschungsprojekten und akademischen Initiativen mit Studenten aus ganz Europa.',
    'features.mentorship.title': 'Grenzüberschreitende Mentorschaft',
    'features.mentorship.description': 'Erhalte Anleitung von erfahrenen Pädagogen und Fachleuten aus verschiedenen europäischen Ländern.',
    'features.resources.title': 'Geteilte Lernressourcen',
    'features.resources.description': 'Zugang zu Bildungsmaterialien, Kursen und Ressourcen, die von der europäischen Lerngemeinschaft geteilt werden.',
    'services.title': 'Bildungsdienste',
    'services.subtitle': 'Umfassende Bildungsunterstützungsdienste, die europäische Studenten und Institutionen verbinden.',
    'services.online.title': 'Online-Lernplattformen',
    'services.online.description': 'Zugang zu Kursen und Bildungsinhalten von Top-Universitäten und Institutionen Europas.',
    'services.exchange.title': 'Studentenaustauschprogramme',
    'services.exchange.description': 'Teilnahme an Austauschprogrammen und Studienaufenthalten in ganz Europa.',
    'services.language.title': 'Sprachlernunterstützung',
    'services.language.description': 'Umfassende Sprachlernprogramme mit Muttersprachlern aus ganz Europa.',
    'services.research.title': 'Kollaborative Forschung',
    'services.research.description': 'Beteilige dich an internationalen Forschungsprojekten und akademischen Kooperationen.',
    'community.title': 'Europäische Lerngemeinschaft',
    'community.subtitle': 'Verbinde dich mit Studenten, Pädagogen und Institutionen aus ganz Europa in unserer lebendigen Lerngemeinschaft.',
    'community.chat.title': 'Gemeinschafts-Chat',
    'community.chat.description': 'Beteilige dich an Echtzeit-Diskussionen mit Mitstudenten und Pädagogen aus ganz Europa.',
    'community.forums.title': 'Lerngruppen & Foren',
    'community.forums.description': 'Teilnahme an fachspezifischen Lerngruppen und akademischen Diskussionen.',
    'community.events.title': 'Bildungsveranstaltungen',
    'community.events.description': 'Teilnahme an Webinaren, Workshops und virtuellen Konferenzen europäischer Institutionen.',
    'footer.company': 'Grenzenlos Lernen',
    'footer.description': 'Verbindung europäischer Studenten und Pädagogen zur Schaffung eines einheitlichen Lernökosystems über alle Grenzen hinweg. Bildung kennt keine Grenzen.',
    'auth.login': 'Anmelden',
    'auth.register': 'Registrieren',
    'auth.email': 'E-Mail',
    'auth.password': 'Passwort',
    'auth.confirmPassword': 'Passwort Bestätigen',
    'auth.forgotPassword': 'Passwort Vergessen?',
    'auth.noAccount': 'Kein Konto?',
    'auth.hasAccount': 'Bereits ein Konto?',
    'chat.placeholder': 'Nachricht eingeben...',
    'chat.send': 'Senden',
    'chat.online': 'Online'
  },
  fr: {
    'nav.home': 'Accueil',
    'nav.mission': 'Mission',
    'nav.features': 'Fonctionnalités',
    'nav.services': 'Services',
    'nav.community': 'Communauté',
    'nav.dashboard': 'Tableau de Bord',
    'nav.signIn': 'Se Connecter',
    'nav.getStarted': 'Commencer',
    'hero.title1': 'Connecter les',
    'hero.title2': 'Étudiants & Éducateurs',
    'hero.title3': 'Européens',
    'hero.subtitle': 'Combler les lacunes éducatives et favoriser la collaboration entre étudiants, éducateurs et institutions à travers l\'Europe. Partagez les connaissances, apprenez les langues et créez des connexions académiques durables.',
    'hero.startJourney': 'Commencez Votre Parcours d\'Apprentissage',
    'hero.learnMore': 'En Savoir Plus',
    'stats.members': 'Membres Étudiants',
    'stats.countries': 'Pays',
    'stats.support': 'Support Éducatif',
    'mission.title': 'Notre Mission Éducative',
    'mission.description': 'Chez Borderless Learning, nous croyons que l\'éducation et le partage des connaissances devraient transcender les frontières nationales. Notre mission est de créer un écosystème éducatif européen unifié où les étudiants et les éducateurs peuvent collaborer, apprendre les uns des autres et construire ensemble l\'avenir de l\'Europe.',
    'features.title': 'Apprentissage Sans Frontières',
    'features.subtitle': 'Découvrez notre suite complète de fonctionnalités éducatives conçues pour connecter les étudiants et éducateurs européens, facilitant l\'échange de connaissances et l\'apprentissage collaboratif à travers le continent.',
    'features.language.title': 'Programmes d\'Échange Linguistique',
    'features.language.description': 'Connectez-vous avec des locuteurs natifs et pratiquez les langues européennes grâce à des programmes d\'échange structurés.',
    'features.academic.title': 'Collaboration Académique',
    'features.academic.description': 'Rejoignez des projets de recherche et des initiatives académiques avec des étudiants de toute l\'Europe.',
    'features.mentorship.title': 'Mentorat Transfrontalier',
    'features.mentorship.description': 'Obtenez des conseils d\'éducateurs expérimentés et de professionnels de différents pays européens.',
    'features.resources.title': 'Ressources d\'Apprentissage Partagées',
    'features.resources.description': 'Accédez aux matériels éducatifs, cours et ressources partagés par la communauté d\'apprentissage européenne.',
    'services.title': 'Services Éducatifs',
    'services.subtitle': 'Services complets de soutien éducatif connectant les étudiants et institutions européens.',
    'services.online.title': 'Plateformes d\'Apprentissage en Ligne',
    'services.online.description': 'Accédez aux cours et contenus éducatifs des meilleures universités et institutions européennes.',
    'services.exchange.title': 'Programmes d\'Échange Étudiant',
    'services.exchange.description': 'Participez aux programmes d\'échange et opportunités d\'études à l\'étranger à travers l\'Europe.',
    'services.language.title': 'Support d\'Apprentissage des Langues',
    'services.language.description': 'Programmes complets d\'apprentissage des langues avec des locuteurs natifs de toute l\'Europe.',
    'services.research.title': 'Recherche Collaborative',
    'services.research.description': 'Rejoignez des projets de recherche internationaux et des collaborations académiques.',
    'community.title': 'Communauté d\'Apprentissage Européenne',
    'community.subtitle': 'Connectez-vous avec des étudiants, éducateurs et institutions de toute l\'Europe dans notre communauté d\'apprentissage dynamique.',
    'community.chat.title': 'Chat Communautaire',
    'community.chat.description': 'Beteilige dich an Echtzeit-Diskussionen mit Mitstudenten und Pädagogen aus ganz Europa.',
    'community.forums.title': 'Groupes d\'Étude & Forums',
    'community.forums.description': 'Teilnahme an fachspezifischen Lerngruppen und akademischen Diskussionen.',
    'community.events.title': 'Événements Éducatifs',
    'community.events.description': 'Teilnahme an Webinaren, ateliers et conférences virtuelles organisés par des institutions européennes.',
    'footer.company': 'Apprentissage Sans Frontières',
    'footer.description': 'Connecter les étudiants et éducateurs européens pour créer un écosystème d\'apprentissage unifié au-delà de toutes les frontières. L\'éducation ne connaît pas de frontières.',
    'auth.login': 'Connexion',
    'auth.register': 'S\'inscrire',
    'auth.email': 'Email',
    'auth.password': 'Mot de Passe',
    'auth.confirmPassword': 'Confirmer le Mot de Passe',
    'auth.forgotPassword': 'Mot de Passe Oublié?',
    'auth.noAccount': 'Pas de compte?',
    'auth.hasAccount': 'Déjà un compte?',
    'chat.placeholder': 'Tapez votre message...',
    'chat.send': 'Envoyer',
    'chat.online': 'En ligne'
  },
  es: {
    'nav.home': 'Inicio',
    'nav.mission': 'Misión',
    'nav.features': 'Características',
    'nav.services': 'Servicios',
    'nav.community': 'Comunidad',
    'nav.dashboard': 'Panel',
    'nav.signIn': 'Iniciar Sesión',
    'nav.getStarted': 'Comenzar',
    'hero.title1': 'Conecta Estudiantes',
    'hero.title2': 'y Educadores',
    'hero.title3': 'Europeos',
    'hero.subtitle': 'Cierra brechas educativas y fomenta la colaboración entre estudiantes, educadores e instituciones en toda Europa.',
    'hero.startJourney': 'Comienza Tu Viaje de Aprendizaje',
    'hero.learnMore': 'Saber Más',
    'stats.members': 'Miembros Estudiantes',
    'stats.countries': 'Países',
    'stats.support': 'Soporte Educativo',
    'mission.title': 'Nuestra Misión Educativa',
    'mission.description': 'En Borderless Learning, creemos que la educación y el intercambio de conocimientos deben trascender las fronteras nacionales.',
    'features.title': 'Aprendizaje Sin Fronteras',
    'features.subtitle': 'Descubre nuestro conjunto completo de características educativas.',
    'footer.company': 'Aprendizaje Sin Fronteras',
    'footer.description': 'Conectando estudiantes y educadores europeos para crear un ecosistema de aprendizaje unificado.',
    'auth.login': 'Iniciar Sesión',
    'auth.register': 'Registrarse',
    'auth.email': 'Correo',
    'auth.password': 'Contraseña',
    'auth.confirmPassword': 'Confirmar Contraseña',
    'auth.forgotPassword': '¿Olvidaste la Contraseña?',
    'auth.noAccount': '¿No tienes cuenta?',
    'auth.hasAccount': '¿Ya tienes cuenta?',
    'chat.placeholder': 'Escribe tu mensaje...',
    'chat.send': 'Enviar',
    'chat.online': 'En línea'
  },
  it: {
    'nav.home': 'Home',
    'nav.mission': 'Missione',
    'nav.features': 'Caratteristiche',
    'nav.services': 'Servizi',
    'nav.community': 'Comunità',
    'nav.dashboard': 'Dashboard',
    'nav.signIn': 'Accedi',
    'nav.getStarted': 'Inizia',
    'hero.title1': 'Connetti Studenti',
    'hero.title2': 'ed Educatori',
    'hero.title3': 'Europei',
    'hero.subtitle': 'Colma le lacune educative e promuovi la collaborazione tra studenti, educatori e istituzioni in tutta Europa.',
    'hero.startJourney': 'Inizia Il Tuo Viaggio di Apprendimento',
    'hero.learnMore': 'Scopri di Più',
    'stats.members': 'Membri Studenti',
    'stats.countries': 'Paesi',
    'stats.support': 'Supporto Educativo',
    'mission.title': 'La Nostra Missione Educativa',
    'mission.description': 'In Borderless Learning, crediamo che l\'educazione e la condivisione della conoscenza dovrebbero trascendere i confini nazionali.',
    'features.title': 'Apprendimento Senza Confini',
    'features.subtitle': 'Scopri la nostra suite completa di funzionalità educative.',
    'footer.company': 'Apprendimento Senza Confini',
    'footer.description': 'Connettere studenti ed educatori europei per creare un ecosistema di apprendimento unificato.',
    'auth.login': 'Accedi',
    'auth.register': 'Registrati',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Conferma Password',
    'auth.forgotPassword': 'Password Dimenticata?',
    'auth.noAccount': 'Non hai un account?',
    'auth.hasAccount': 'Hai già un account?',
    'chat.placeholder': 'Scrivi il tuo messaggio...',
    'chat.send': 'Invia',
    'chat.online': 'Online'
  },
  pt: {
    'nav.home': 'Início',
    'nav.mission': 'Missão',
    'nav.features': 'Recursos',
    'nav.services': 'Serviços',
    'nav.community': 'Comunidade',
    'nav.dashboard': 'Painel',
    'nav.signIn': 'Entrar',
    'nav.getStarted': 'Começar',
    'hero.title1': 'Conecte Estudantes',
    'hero.title2': 'e Educadores',
    'hero.title3': 'Europeus',
    'hero.subtitle': 'Feche lacunas educacionais e promova colaboração entre estudantes, educadores e instituições em toda a Europa.',
    'hero.startJourney': 'Comece Sua Jornada de Aprendizado',
    'hero.learnMore': 'Saiba Mais',
    'stats.members': 'Membros Estudantes',
    'stats.countries': 'Países',
    'stats.support': 'Suporte Educacional',
    'mission.title': 'Nossa Missão Educacional',
    'mission.description': 'Na Borderless Learning, acreditamos que educação e compartilhamento de conhecimento devem transcender fronteiras nacionais.',
    'features.title': 'Aprendizado Sem Fronteiras',
    'features.subtitle': 'Descubra nosso conjunto abrangente de recursos educacionais.',
    'footer.company': 'Aprendizado Sem Fronteiras',
    'footer.description': 'Conectando estudantes e educadores europeus para criar um ecossistema de aprendizado unificado.',
    'auth.login': 'Entrar',
    'auth.register': 'Registrar',
    'auth.email': 'Email',
    'auth.password': 'Senha',
    'auth.confirmPassword': 'Confirmar Senha',
    'auth.forgotPassword': 'Esqueceu a Senha?',
    'auth.noAccount': 'Não tem conta?',
    'auth.hasAccount': 'Já tem conta?',
    'chat.placeholder': 'Digite sua mensagem...',
    'chat.send': 'Enviar',
    'chat.online': 'Online'
  },
  nl: {
    'nav.home': 'Home',
    'nav.mission': 'Missie',
    'nav.features': 'Functies',
    'nav.services': 'Diensten',
    'nav.community': 'Gemeenschap',
    'nav.dashboard': 'Dashboard',
    'nav.signIn': 'Inloggen',
    'nav.getStarted': 'Beginnen',
    'hero.title1': 'Verbind Europese',
    'hero.title2': 'Studenten & Docenten',
    'hero.title3': 'Over Grenzen',
    'hero.subtitle': 'Overbruggen van educatieve kloven en bevorderen van samenwerking tussen studenten, docenten en instellingen in heel Europa.',
    'hero.startJourney': 'Begin Je Leerreis',
    'hero.learnMore': 'Meer Leren',
    'stats.members': 'Student Leden',
    'stats.countries': 'Landen',
    'stats.support': 'Educatieve Ondersteuning',
    'mission.title': 'Onze Educatieve Missie',
    'mission.description': 'Bij Borderless Learning geloven we dat onderwijs en kennisdeling nationale grenzen moet overstijgen.',
    'features.title': 'Leren Zonder Grenzen',
    'features.subtitle': 'Ontdek onze uitgebreide suite van educatieve functies.',
    'footer.company': 'Leren Zonder Grenzen',
    'footer.description': 'Europese studenten en docenten verbinden om een verenigd leerecosysteem te creëren.',
    'auth.login': 'Inloggen',
    'auth.register': 'Registreren',
    'auth.email': 'Email',
    'auth.password': 'Wachtwoord',
    'auth.confirmPassword': 'Bevestig Wachtwoord',
    'auth.forgotPassword': 'Wachtwoord Vergeten?',
    'auth.noAccount': 'Geen account?',
    'auth.hasAccount': 'Al een account?',
    'chat.placeholder': 'Typ je bericht...',
    'chat.send': 'Verzenden',
    'chat.online': 'Online'
  },
  sv: {
    'nav.home': 'Hem',
    'nav.mission': 'Mission',
    'nav.features': 'Funktioner',
    'nav.services': 'Tjänster',
    'nav.community': 'Gemenskap',
    'nav.dashboard': 'Dashboard',
    'nav.signIn': 'Logga In',
    'nav.getStarted': 'Kom Igång',
    'hero.title1': 'Anslut Europeiska',
    'hero.title2': 'Studenter & Lärare',
    'hero.title3': 'Över Gränser',
    'hero.subtitle': 'Överbrygga utbildningsklyftor och främja samarbete mellan studenter, lärare och institutioner över hela Europa.',
    'hero.startJourney': 'Börja Din Inlärningsresa',
    'hero.learnMore': 'Lär Dig Mer',
    'stats.members': 'Student Medlemmar',
    'stats.countries': 'Länder',
    'stats.support': 'Utbildningsstöd',
    'mission.title': 'Vårt Utbildningsuppdrag',
    'mission.description': 'På Borderless Learning tror vi att utbildning och kunskapsdeling bör överskrida nationella gränser.',
    'features.title': 'Lärande Utan Gränser',
    'features.subtitle': 'Upptäck vårt omfattande utbud av utbildningsfunktioner.',
    'footer.company': 'Lärande Utan Gränser',
    'footer.description': 'Förbinder europeiska studenter och lärare för att skapa ett enhetligt inlärningsekosystem.',
    'auth.login': 'Logga In',
    'auth.register': 'Registrera',
    'auth.email': 'Email',
    'auth.password': 'Lösenord',
    'auth.confirmPassword': 'Bekräfta Lösenord',
    'auth.forgotPassword': 'Glömt Lösenord?',
    'auth.noAccount': 'Inget konto?',
    'auth.hasAccount': 'Har redan konto?',
    'chat.placeholder': 'Skriv ditt meddelande...',
    'chat.send': 'Skicka',
    'chat.online': 'Online'
  },
  da: {
    'nav.home': 'Hjem',
    'nav.mission': 'Mission',
    'nav.features': 'Funktioner',
    'nav.services': 'Tjenester',
    'nav.community': 'Fællesskab',
    'nav.dashboard': 'Dashboard',
    'nav.signIn': 'Log Ind',
    'nav.getStarted': 'Kom I Gang',
    'hero.title1': 'Forbind Europæiske',
    'hero.title2': 'Studenter & Lærere',
    'hero.title3': 'På Tværs af Grænser',
    'hero.subtitle': 'Bygge bro over uddannelsesmæssige kløfter og fremme samarbejde mellem studenter, lærere og institutioner på tværs af Europa.',
    'hero.startJourney': 'Start Din Indlæringsrejse',
    'hero.learnMore': 'Lær Mere',
    'stats.members': 'Student Medlemmer',
    'stats.countries': 'Lande',
    'stats.support': 'Uddannelsesstøtte',
    'mission.title': 'Vores Uddannelsesmission',
    'mission.description': 'Hos Borderless Learning tror vi, at uddannelse og vidensdeling bør overskride nationale grænser.',
    'features.title': 'Læring Uden Grænser',
    'features.subtitle': 'Opdag vores omfattende pakke af uddannelsesfunktioner.',
    'footer.company': 'Læring Uden Grænser',
    'footer.description': 'Forbinder europæiske studenter og lærere for at skabe et forenet læringsøkosystem.',
    'auth.login': 'Log Ind',
    'auth.register': 'Tilmeld',
    'auth.email': 'Email',
    'auth.password': 'Adgangskode',
    'auth.confirmPassword': 'Bekræft Adgangskode',
    'auth.forgotPassword': 'Glemt Adgangskode?',
    'auth.noAccount': 'Ingen konto?',
    'auth.hasAccount': 'Har allerede konto?',
    'chat.placeholder': 'Skriv din besked...',
    'chat.send': 'Send',
    'chat.online': 'Online'
  },
  no: {
    'nav.home': 'Hjem',
    'nav.mission': 'Misjon',
    'nav.features': 'Funksjoner',
    'nav.services': 'Tjenester',
    'nav.community': 'Fellesskap',
    'nav.dashboard': 'Dashboard',
    'nav.signIn': 'Logg Inn',
    'nav.getStarted': 'Kom I Gang',
    'hero.title1': 'Koble Europeiske',
    'hero.title2': 'Studenter & Lærere',
    'hero.title3': 'På Tvers av Grenser',
    'hero.subtitle': 'Bygge broer over utdanningsgap og fremme samarbeid mellom studenter, lærere og institusjoner på tvers av Europa.',
    'hero.startJourney': 'Start Din Læringsreise',
    'hero.learnMore': 'Lær Mer',
    'stats.members': 'Student Medlemmer',
    'stats.countries': 'Land',
    'stats.support': 'Utdanningsstøtte',
    'mission.title': 'Vårt Utdanningsoppdrag',
    'mission.description': 'Hos Borderless Learning tror vi at utdanning og kunnskapsdeling bør overskride nasjonale grenser.',
    'features.title': 'Læring Uten Grenser',
    'features.subtitle': 'Oppdag vår omfattende pakke med utdanningsfunksjoner.',
    'footer.company': 'Læring Uten Grenser',
    'footer.description': 'Kobler europeiske studenter og lærere for å skape et enhetlig læringsøkosystem.',
    'auth.login': 'Logg Inn',
    'auth.register': 'Registrer',
    'auth.email': 'Email',
    'auth.password': 'Passord',
    'auth.confirmPassword': 'Bekreft Passord',
    'auth.forgotPassword': 'Glemt Passord?',
    'auth.noAccount': 'Ingen konto?',
    'auth.hasAccount': 'Har allerede konto?',
    'chat.placeholder': 'Skriv din melding...',
    'chat.send': 'Send',
    'chat.online': 'Online'
  },
  fi: {
    'nav.home': 'Koti',
    'nav.mission': 'Missio',
    'nav.features': 'Ominaisuudet',
    'nav.services': 'Palvelut',
    'nav.community': 'Yhteisö',
    'nav.dashboard': 'Kojelauta',
    'nav.signIn': 'Kirjaudu',
    'nav.getStarted': 'Aloita',
    'hero.title1': 'Yhdistä Eurooppalaisia',
    'hero.title2': 'Opiskelijoita & Opettajia',
    'hero.title3': 'Rajojen Yli',
    'hero.subtitle': 'Kuroa umpeen koulutuskuiluja ja edistä yhteistyötä opiskelijoiden, opettajien ja oppilaitosten välillä koko Euroopassa.',
    'hero.startJourney': 'Aloita Oppimismatkasi',
    'hero.learnMore': 'Lue Lisää',
    'stats.members': 'Opiskelija Jäsenet',
    'stats.countries': 'Maat',
    'stats.support': 'Koulutustuki',
    'mission.title': 'Meidän Koulutusmissiomme',
    'mission.description': 'Borderless Learningissa uskomme, että koulutuksen ja tiedonjaon tulisi ylittää kansalliset rajat.',
    'features.title': 'Oppiminen Ilman Rajoja',
    'features.subtitle': 'Tutustu kattavaan koulutusominaisuuksiemme valikoimaan.',
    'footer.company': 'Oppiminen Ilman Rajoja',
    'footer.description': 'Yhdistää eurooppalaisia opiskelijoita ja opettajia luomaan yhtenäisen oppimisekosysteemin.',
    'auth.login': 'Kirjaudu',
    'auth.register': 'Rekisteröidy',
    'auth.email': 'Sähköposti',
    'auth.password': 'Salasana',
    'auth.confirmPassword': 'Vahvista Salasana',
    'auth.forgotPassword': 'Unohtunut Salasana?',
    'auth.noAccount': 'Ei tiliä?',
    'auth.hasAccount': 'Onko sinulla jo tili?',
    'chat.placeholder': 'Kirjoita viestisi...',
    'chat.send': 'Lähetä',
    'chat.online': 'Online'
  },
  pl: {
    'nav.home': 'Strona Główna',
    'nav.mission': 'Misja',
    'nav.features': 'Funkcje',
    'nav.services': 'Usługi',
    'nav.community': 'Społeczność',
    'nav.dashboard': 'Panel',
    'nav.signIn': 'Zaloguj',
    'nav.getStarted': 'Zacznij',
    'hero.title1': 'Połącz Europejskich',
    'hero.title2': 'Studentów i Nauczycieli',
    'hero.title3': 'Przez Granice',
    'hero.subtitle': 'Łączyć luki edukacyjne i wspierać współpracę między studentami, nauczycielami i instytucjami w całej Europie.',
    'hero.startJourney': 'Rozpocznij Swoją Podróż Edukacyjną',
    'hero.learnMore': 'Dowiedz Się Więcej',
    'stats.members': 'Członkowie Studenci',
    'stats.countries': 'Kraje',
    'stats.support': 'Wsparcie Edukacyjne',
    'mission.title': 'Nasza Misja Edukacyjna',
    'mission.description': 'W Borderless Learning wierzymy, że edukacja i dzielenie się wiedzą powinno przekraczać granice narodowe.',
    'features.title': 'Nauka Bez Granic',
    'features.subtitle': 'Odkryj nasz kompleksowy zestaw funkcji edukacyjnych.',
    'footer.company': 'Nauka Bez Granic',
    'footer.description': 'Łączenie europejskich studentów i nauczycieli w celu stworzenia zunifikowanego ekosystemu nauki.',
    'auth.login': 'Zaloguj',
    'auth.register': 'Zarejestruj',
    'auth.email': 'Email',
    'auth.password': 'Hasło',
    'auth.confirmPassword': 'Potwierdź Hasło',
    'auth.forgotPassword': 'Zapomniałeś Hasła?',
    'auth.noAccount': 'Nie masz konta?',
    'auth.hasAccount': 'Masz już konto?',
    'chat.placeholder': 'Wpisz swoją wiadomość...',
    'chat.send': 'Wyślij',
    'chat.online': 'Online'
  },
  ru: {
    'nav.home': 'Главная',
    'nav.mission': 'Миссия',
    'nav.features': 'Возможности',
    'nav.services': 'Услуги',
    'nav.community': 'Сообщество',
    'nav.dashboard': 'Панель',
    'nav.signIn': 'Войти',
    'nav.getStarted': 'Начать',
    'hero.title1': 'Связать Европейских',
    'hero.title2': 'Студентов и Преподавателей',
    'hero.title3': 'Через Границы',
    'hero.subtitle': 'Преодолевать образовательные пробелы и способствовать сотрудничеству между студентами, преподавателями и учреждениями по всей Европе.',
    'hero.startJourney': 'Начните Ваше Образовательное Путешествие',
    'hero.learnMore': 'Узнать Больше',
    'stats.members': 'Участники Студенты',
    'stats.countries': 'Страны',
    'stats.support': 'Образовательная Поддержка',
    'mission.title': 'Наша Образовательная Миссия',
    'mission.description': 'В Borderless Learning мы верим, что образование и обмен знаниями должны преодолевать национальные границы.',
    'features.title': 'Обучение Без Границ',
    'features.subtitle': 'Откройте для себя наш комплексный набор образовательных функций.',
    'footer.company': 'Обучение Без Границ',
    'footer.description': 'Соединяя европейских студентов и преподавателей для создания единой образовательной экосистемы.',
    'auth.login': 'Войти',
    'auth.register': 'Зарегистрироваться',
    'auth.email': 'Email',
    'auth.password': 'Пароль',
    'auth.confirmPassword': 'Подтвердить Пароль',
    'auth.forgotPassword': 'Забыли Пароль?',
    'auth.noAccount': 'Нет аккаунта?',
    'auth.hasAccount': 'Уже есть аккаунт?',
    'chat.placeholder': 'Введите ваше сообщение...',
    'chat.send': 'Отправить',
    'chat.online': 'Онлайн'
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};